// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVl261oqZmmFw7FzSWlBBBv8APT8UVh8E',
    appId: '1:95429561014:web:36fdea627781e819bfb417',
    messagingSenderId: '95429561014',
    projectId: 'gulf-limousine-travel',
    authDomain: 'gulf-limousine-travel.firebaseapp.com',
    storageBucket: 'gulf-limousine-travel.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuU9mfGretUm3t1o47U4kc2v30dmGCN6E',
    appId: '1:95429561014:android:c12c4b753467d1c1bfb417',
    messagingSenderId: '95429561014',
    projectId: 'gulf-limousine-travel',
    storageBucket: 'gulf-limousine-travel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKHJ2-8SrEI8Y23ffGWzjUzVB91zL1T24',
    appId: '1:95429561014:ios:fffb76aaf34b5efbbfb417',
    messagingSenderId: '95429561014',
    projectId: 'gulf-limousine-travel',
    storageBucket: 'gulf-limousine-travel.firebasestorage.app',
    androidClientId: '95429561014-n8i9i0anm6ck6lle5qlb2l04u4irvl6o.apps.googleusercontent.com',
    iosClientId: '95429561014-kobrj51j7dms1tefia39j3o8f8bt2ma6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gLTFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKHJ2-8SrEI8Y23ffGWzjUzVB91zL1T24',
    appId: '1:95429561014:ios:fffb76aaf34b5efbbfb417',
    messagingSenderId: '95429561014',
    projectId: 'gulf-limousine-travel',
    storageBucket: 'gulf-limousine-travel.firebasestorage.app',
    androidClientId: '95429561014-n8i9i0anm6ck6lle5qlb2l04u4irvl6o.apps.googleusercontent.com',
    iosClientId: '95429561014-kobrj51j7dms1tefia39j3o8f8bt2ma6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gLTFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVl261oqZmmFw7FzSWlBBBv8APT8UVh8E',
    appId: '1:95429561014:web:94a8ce6fb24876b0bfb417',
    messagingSenderId: '95429561014',
    projectId: 'gulf-limousine-travel',
    authDomain: 'gulf-limousine-travel.firebaseapp.com',
    storageBucket: 'gulf-limousine-travel.firebasestorage.app',
  );
}
